### ISSUE TITLE
remove pyscript information elements when loading "pyscript" module

### ISSUE THREAD

**Issue by noel-friedrich** [noel-friedrich/terminal#2]

**Comment by noel-friedrich** [comment]
solved by adding the follow css selector to style.css
```css
py-splashscreen {
    display: none;
}
```
